use github sha and proper hash

diff --git a/.github/workflows/pipeline_assembly.yaml b/.github/workflows/pipeline_assembly.yaml
--- a/.github/workflows/pipeline_assembly.yaml
+++ b/.github/workflows/pipeline_assembly.yaml
@@ -33,6 +33,10 @@ jobs:
         shell: bash -l {0}
         run: |
           nextflow pull ktmeaton/plague-phylogeography
+          nextflow pull ktmeaton/plague-phylogeography -r ${GITHUB_SHA}
+          # Move env files into github workspace for hashing
+          cp ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml \
+            ./ktmeaton-plague-phylogeography.yaml
       #------------------------------------------------------------------------#
       #  Restore (cache) conda environments
       - name: setup conda
@@ -44,7 +48,7 @@ jobs:
         with:
           path: |
             /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
-          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml') }}
+          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./ktmeaton-plague-phylogeography.yaml') }}
       #------------------------------------------------------------------------#
       # Check conda environments
       - name: check cache
@@ -52,7 +56,9 @@ jobs:
       #  Fail workflow if cache not restored
       - name: fail cache
         if:  steps.plague-phylogeography-env-cache-restore.outputs.cache-hit != 'true'
-        run: exit 1
+        run: |
+          echo "plague-phylogeography cache failed to load."
+          exit 1
       #------------------------------------------------------------------------#
       #  Test Pipeline
       - name: pipeline
@@ -60,7 +66,7 @@ jobs:
         shell: bash -l {0}
         run: |
           conda activate ${PHYLO_CONDA_ENV}
-          nextflow run ktmeaton/plague-phylogeography \
+          nextflow run -r ${GITHUB_SHA} ktmeaton/plague-phylogeography \
             --max_datasets_assembly 2 \
             --skip_sra_download \
             --skip_eager \
