add 2 hour timeout limit

diff --git a/.github/workflows/pipeline_sra.yaml b/.github/workflows/pipeline_sra.yaml
--- a/.github/workflows/pipeline_sra.yaml
+++ b/.github/workflows/pipeline_sra.yaml
@@ -1,138 +1,107 @@
+#------------------------------------------------------------------------------#
 name: Pipeline SRA
-#This is a workflow for sra/eager pipeline testing.
-
+#------------------------------------------------------------------------------#
 # Global workflow environment variables
 env:
-    PHYLO_NF_REV: "master"
+    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
     EAGER_NF_REV: "7b51863957"
     PHYLO_CONDA_ENV: "plague-phylogeography-0.1.4dev"
-    EAGER_CONDA_ENV: "nf-core-eager-2.2.0dev"
-
+    CONDA_ENVS_PATH: "/home/runner/miniconda/envs:/usr/share/miniconda/envs"
+    CONDA_PKGS_DIRS: "/home/runner/miniconda/pkgs"
+    GH_RESOURCES:    "--max_memory '6.GB' --max_cpus 2"
+#------------------------------------------------------------------------------#
+# Workflow conditions
 on:
-  # Triggered on Push for any branch
   push:
     branches:
       - '*'
-    # On change to workflow, pipeline
     paths:
       - '.github/workflows/pipeline_sra.yaml'
       - 'main.nf'
       - 'nextflow.config'
-      - 'environment.yaml'
-
-  # Triggered on PR for all branches, pipeline
-  pull_request:
-    branches:
-      - '*'
-  # Also on a published release
-  release:
-    types: [published]
-
+#------------------------------------------------------------------------------#
 jobs:
-
-  # Install the pipeline and dependencies
-  pipeline:
+  #----------------------------------------------------------------------------#
+  # Install dependencies
+  install :
     runs-on: ubuntu-latest
+    timeout-minutes: 120
     steps:
-
-      # 1. Install nextflow
+      #------------------------------------------------------------------------#
+      # Install nextflow
       - name: install nextflow
         run: |
           wget -qO- get.nextflow.io | bash
           sudo mv nextflow /usr/local/bin/
-
-      # 2. Setup conda
-      - name: setup conda
-        uses: goanpeca/setup-miniconda@v1
-        with:
-          auto-update-conda: true
-
-      # 3a. Install ktmeaton/plague-phylogeography
-      - name: install nf ktmeaton/plague-phylogeography
-        shell: bash -l {0}
-        run: |
-          nextflow pull ktmeaton/plague-phylogeography
-          nextflow pull ktmeaton/plague-phylogeography -r ${PHYLO_NF_REV}
-          nextflow run ktmeaton/plague-phylogeography --version
-
-      # 3b. Install ktmeaton/plague-phylogeography
-      - name: install conda ktmeaton/plague-phylogeography
-        shell: bash -l {0}
-        run: |
-          conda env create -f  ~/.nextflow/assets/ktmeaton/plague-phylogeography/environment.yaml
-          conda activate ${PHYLO_CONDA_ENV}
-          conda deactivate
-
-      # 4a. Install nf-core/eager
-      - name: install nf nf-core/eager
+      #------------------------------------------------------------------------#
+      # download nextflow pipelines
+      - name: download nf-core/eager
         shell: bash -l {0}
         run: |
           nextflow pull nf-core/eager
           nextflow pull nf-core/eager -r ${EAGER_NF_REV}
           nextflow run nf-core/eager -r ${EAGER_NF_REV} --help
+          # Move env file into github workspace for hashing
+          cp ~/.nextflow/assets/nf-core/eager/environment.yml \
+            ./nf-core-eager.yaml
 
-      # 4b. Install nf-core/eager
-      - name: install conda nf-core/eager
+      - name: download plague-phylogeography
         shell: bash -l {0}
         run: |
-          conda env create -f ~/.nextflow/assets/nf-core/eager/environment.yml
-          conda install -n ${EAGER_CONDA_ENV} -c bioconda nextflow
-          conda install -n ${EAGER_CONDA_ENV} -c anaconda graphviz
-          conda activate ${EAGER_CONDA_ENV}
-          dot -v
-          nextflow -v
-          conda deactivate
+          nextflow pull ${GITHUB_REPOSITORY}
+          nextflow pull ${GITHUB_REPOSITORY} -r ${GITHUB_SHA}
+          nextflow run ${GITHUB_REPOSITORY} --version
+          # Move env files into github workspace for hashing
+          cp ~/.nextflow/assets/${GITHUB_REPOSITORY}/environment.yaml \
+            ./plague-phylogeography.yaml
+      #------------------------------------------------------------------------#
+      #  Restore (cache) conda environments
+      - name: setup conda
+        uses: goanpeca/setup-miniconda@v1
 
-      - name: example pipeline
+      - name: restore eager cache
+        uses: actions/cache@v2
+        id: eager-env-cache
+        with:
+          path: |
+            /home/runner/miniconda/envs/nf-core-eager-2.2.0dev
+          key: eager-env-cache-${{ runner.os }}-test2-${{ hashFiles('./nf-core-eager.yaml') }}
+
+      - name: restore plague-phylogeography cache
+        uses: actions/cache@v2
+        id: plague-phylogeography-env-cache
+        with:
+          path: |
+            /home/runner/miniconda/envs/plague-phylogeography-0.1.4dev
+          key: plague-phylogeography-env-cache-${{ runner.os }}-test2-${{ hashFiles('./plague-phylogeography.yaml') }}
+      #------------------------------------------------------------------------#
+      # Check conda environments
+      - name: check cache
+        run: conda info --envs
+      #  Fail workflows if cache not restored
+      - name: fail eager cache
+        if:  steps.eager-env-cache-restore.outputs.cache-hit != 'true'
+        run: |
+          echo "eager cache failed to load."
+          exit 1
+      - name: fail plague-phylogeography cache
+        if:  steps.plague-phylogeography-env-cache-restore.outputs.cache-hit != 'true'
+        run: |
+          echo "plague-phylogeography cache failed to load."
+          exit 1
+      #------------------------------------------------------------------------#
+      #  Download SRA Data
+      - name: pipeline sra download
+        if:  steps.plague-phylogeography-env-cache-restore.outputs.cache-hit == 'true' && steps.eager-env-cache-restore.outputs.cache-hit == 'true'
         shell: bash -l {0}
         run: |
           conda activate ${PHYLO_CONDA_ENV}
-          nextflow run ktmeaton/plague-phylogeography \
+          nextflow run -r ${GITHUB_SHA} ${GITHUB_REPOSITORY} \
             --skip_assembly_download \
             --max_datasets_assembly 1 \
             --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
             --skip_eager \
             --skip_outgroup_download \
             --outdir test \
-            --max_memory "6.GB" \
-            --max_cpus 2
+            ${GH_RESOURCES}
           conda deactivate
-
-      - name: example eager
-        shell: bash -l {0}
-        run: |
-          conda activate ${PHYLO_CONDA_ENV}
-          nextflow run ktmeaton/plague-phylogeography \
-            --skip_assembly_download \
-            --max_datasets_assembly 1 \
-            --sqlite_select_command_sra "\"SELECT BioSampleAccession,SRARunAccession,SRALibraryLayout,SRAFileURL FROM Master WHERE (SRARunAccession = 'SRR1048902' OR SRARunAccession = 'SRR1048905')\"" \
-            --skip_outgroup_download \
-            --outdir test \
-            --max_memory "6.GB" \
-            --max_cpus 2 \
-            -resume
-          conda deactivate
-
-      - name: artifact sqlite-import
-        uses: actions/upload-artifact@v2
-        with:
-          name: sqlite-import
-          path: test/sqlite_import/
-
-      - name: artifact iqtree
-        uses: actions/upload-artifact@v2
-        with:
-          name: iqtree
-          path: test/iqtree/
-
-      - name: artifact multiqc
-        uses: actions/upload-artifact@v2
-        with:
-          name: multiqc
-          path: test/eager/MultiQC
-
-      - name: artifact trace
-        uses: actions/upload-artifact@v2
-        with:
-          name: trace
-          path: test/trace/
